edu.unibo.flickr_images: #{group_id}.{name} from the knime.yml
  src: C:/Users/Alberto/Desktop/knime-python-flickr # Local path to folder containing the extension files
  conda_env_path:  C:\Users\Alberto\anaconda3\envs\my_python_env  # Path to the local installed Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform